#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=00
STOP=90

RTC_DEV=/dev/rtc0
HWCLOCK=/sbin/hwclock

fallback_date="2025-08-05 00:00:00"

boot() {
    start && exit 0

    local maxtime="$(maxtime)"
    local curtime="$(date +%s)"
    [ $curtime -lt $maxtime ] && date -s @$maxtime
}

start() {
    if [ -e "$RTC_DEV" ] && [ -e "$HWCLOCK" ]; then
        $HWCLOCK -s -u -f $RTC_DEV
    else
        echo "RTC or hwclock failed, setting fallback date."
        date -s "$fallback_date"
    fi
}

stop() {
    [ -e "$RTC_DEV" ] && [ -e "$HWCLOCK" ] && $HWCLOCK -w -u -f $RTC_DEV && \
        logger -t sysfixtime "saved '$(date)' to $RTC_DEV"
}

maxtime() {
    local file newest

    for file in $( find /etc -type f ) ; do
        [ -z "$newest" -o "$newest" -ot "$file" ] && newest=$file
    done
    [ "$newest" ] && date -r "$newest" +%s
}
